services:
  client:
    build:
      context: ./ABClient
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '80:3000'

    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules