services:
  client:
    build:
      context: ./ABClient
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - PRIVATE_IP=${PRIVATE_IP}
      - INSTANCE_ID=${INSTANCE_ID}
