services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '80:3000'

    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules