version: '3.9'


services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '80:3000'

    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules